name: Terraform Deploy on Main Branch

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Init and Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Format Check
        run: cd terraform && terraform fmt -check -recursive

      - name: Terraform Validate
        run: cd terraform && terraform validate

      - name: Terraform Plan
        run: cd terraform && terraform plan -out=tfplan

          #      - name: Terraform Apply
          #        run: terraform apply -auto-approve tfplan
